name:  Deploy Laravel to HostGator (separated public)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install TailWindCSS
        run: npm install tailwindcss @tailwindcss/vite

      - name: Build Tailwind CSS
        run: npx tailwindcss -i ./resources/css/input.css -o ./public/css/output.css --minify

      - name: Deploy backend (Laravel)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /laravel/
          exclude: |
            public/**
            */.git
            */node_modules/*
            */docker/*
            */.github/*
            */tests/*
            **/.env.example
            **/README.md
      - name: Deploy public assets
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: public/
          server-dir: /
