name:  Cambios en Develop

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy backend (Laravel)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_DEV }}
          password: ${{ secrets.FTP_PASSWORD_DEV }}
          server-dir: /laravel/
          exclude: |
            */.git
            */node_modules/*
            */docker/*
            */.github/*
            */tests/*
            **/.env.example
            **/README.md
      - name: Deploy public assets
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME_DEV }}
          password: ${{ secrets.FTP_PASSWORD_DEV }}
          local-dir: public/build/
          server-dir: /build/
